### ISSUE TITLE
Utiliser le proxy sur publish_assets

### ISSUE THREAD

**Issue by Arioch171** [le-phare/capistrano-lephare#31]
https://github.com/le-phare/capistrano-lephare/blob/61db995d5a6deef678927b3aafbcab58a1bfbc7a/lib/capistrano/tasks/deploy.rake#L18

**Comment by erichard** [comment]
Feel free to submit a PR :wink:

**Comment by alterphp** [comment]
SSH proxy options should be used for every run_locally commands that uses SSH ?
- shared:pull
- oceanet:log:browse

**Comment by Arioch171** [comment]
Voir #32

**Comment by Arioch171** [comment]
Fixed in 62609345b97c9ca355b436e29acfa7ba685c3868.
